services:
  LDI-postgres:
    image: postgres:16-alpine
    container_name: LDI-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - 5432:5432
    volumes:
      - ldi-postgres-data:/var/lib/postgresql/data

networks:
  default:
    driver: bridge
volumes:
    ldi-postgres-data:
