services:
  LDI-postgres:
    image: postgres:16-alpine
    container_name: LDI-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - 5432:5432
    volumes:
      - ldi-postgres-data:/var/lib/postgresql/data
  LDI-PG:
    image: dpage/pgadmin4:latest
    container_name: LDI-PG
    restart: always
    depends_on:
      - LDI-postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 8080:80
    volumes:
      - ldi-pgadmin-data:/var/lib/pgadmin

networks:
  default:
    name: local-network
    external: true
volumes:
    ldi-postgres-data:
    ldi-pgadmin-data: